name: Jekyll site CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # 3. Install bundler
      - run: gem install bundler

      # 4. Install dependencies from Gemfile
      - run: bundle install

      # 5. Build the site
      - run: bundle exec jekyll build --config _config.yml

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ""
          # For a project site like myrepo, baseurl handles the path
